"""
Intent Detector - Rule-based + weak LLM for structured intent detection
Prevents LLM from controlling workflow logic
"""

from typing import Optional, Dict, Any
from enum import Enum
import re
from modules.common.logger import get_logger

logger = get_logger(__name__)


class UserIntent(str, Enum):
    """Structured intent types - NOT generated by LLM."""
    GREETING = "greeting"
    QUESTION = "question"
    QUALIFICATION = "qualification"
    BOOKING_REQUEST = "booking_request"
    RECOMMENDATION_REQUEST = "recommendation_request"
    CONFIRMATION = "confirmation"
    OBJECTION = "objection"
    FOLLOW_UP = "follow_up"
    COMPLAINT = "complaint"
    UNCLEAR = "unclear"


class IntentDetector:
    """Detects user intent without letting LLM control business logic."""

    # Rule-based patterns for each intent
    INTENT_PATTERNS = {
        UserIntent.BOOKING_REQUEST: [
            r"book|appointment|reserve|table\s*for|site\s*visit|visit|consultation",
            r"tomorrow|next\s*day|time",
            r"when\s*can|how\s*soon|schedule",
        ],
        UserIntent.QUALIFICATION: [
            r"budget|price|cost|how\s*much",
            r"bedroom|bhk|size|area|location|address",
            r"require|need|want|looking\s*for",
        ],
        UserIntent.RECOMMENDATION_REQUEST: [
            r"recommend|suggest|what\s*do\s*you|options|available",
            r"best|suitable|fit|match",
        ],
        UserIntent.CONFIRMATION: [
            r"yes|yep|okay|ok|sure|confirmed|agree|correct|true",
            r"that\s*sounds|looks\s*good",
        ],
        UserIntent.OBJECTION: [
            r"no|not|don't|don't|cannot|can't|won't|shouldn't",
            r"too\s*expensive|expensive|costly|high",
            r"not\s*interested|not\s*suitable",
        ],
        UserIntent.GREETING: [
            r"^(hi|hello|hey|greetings|namaste)",
            r"^(good\s*morning|good\s*afternoon|good\s*evening)",
        ],
        UserIntent.COMPLAINT: [
            r"complaint|issue|problem|wrong|error|not\s*working",
            r"angry|frustrated|upset|disappointed",
        ],
    }

    @staticmethod
    def detect(user_message: str) -> UserIntent:
        """Detect intent using rules, not LLM."""
        message_lower = user_message.lower().strip()

        # Score each intent
        scores = {}
        for intent, patterns in IntentDetector.INTENT_PATTERNS.items():
            matches = sum(
                1 for pattern in patterns
                if re.search(pattern, message_lower, re.IGNORECASE)
            )
            scores[intent] = matches

        # Return highest scoring intent
        if max(scores.values()) > 0:
            detected = max(scores, key=scores.get)
            logger.debug(f"Detected intent: {detected.value} (scores: {scores})")
            return detected

        logger.debug(f"Could not detect intent, defaulting to UNCLEAR")
        return UserIntent.UNCLEAR

    @staticmethod
    def is_affirmative(message: str) -> bool:
        """Simple affirmation detection."""
        patterns = [r"^(yes|yep|okay|ok|sure|confirmed|agree|yeah|yup|true)"]
        return any(re.search(p, message.lower()) for p in patterns)

    @staticmethod
    def is_negative(message: str) -> bool:
        """Simple negation detection."""
        patterns = [r"^(no|nope|not|don't|don't|cannot|can't|won't|false)"]
        return any(re.search(p, message.lower()) for p in patterns)

    @staticmethod
    def extract_entities(user_message: str, intent: UserIntent) -> Dict[str, Any]:
        """Extract entities relevant to detected intent."""
        entities = {}
        message_lower = user_message.lower()

        # Date/time extraction
        if "booking" in intent.value or "appointment" in intent.value:
            # Tomorrow
            if re.search(r"tomorrow|next\s*day", message_lower):
                entities["date_reference"] = "tomorrow"

            # Time extraction (e.g., "1 PM", "13:00")
            time_match = re.search(r"(\d{1,2})\s*(?::(\d{2}))?\s*(am|pm)?", message_lower)
            if time_match:
                hour = int(time_match.group(1))
                minute = int(time_match.group(2)) if time_match.group(2) else 0
                period = time_match.group(3) or ""
                entities["time"] = f"{hour:02d}:{minute:02d}"
                if period:
                    entities["period"] = period

        # Budget extraction
        budget_match = re.search(r"(\d+)\s*(lakh|lac|crore|k|thousand|lacs)", message_lower)
        if budget_match:
            entities["budget"] = budget_match.group(0)

        # BHK/size extraction
        bhk_match = re.search(r"(\d+)\s*bhk", message_lower)
        if bhk_match:
            entities["bhk"] = bhk_match.group(0)

        return entities
