"""initial_schema

Revision ID: a2f3594362bc
Revises: 
Create Date: 2026-05-22 11:40:32.133827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2f3594362bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_message_logs_org'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_table('conversation_custom_field_definitions')
    op.drop_index(op.f('idx_knowledge_chunks_embedding'), table_name='knowledge_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('idx_whatsapp_templates_org'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    op.drop_table('nano_tasks')
    op.drop_constraint(op.f('ai_configurations_organization_id_key'), 'ai_configurations', type_='unique')
    op.drop_index(op.f('idx_blogs_published'), table_name='blogs')
    op.drop_index(op.f('idx_blogs_slug'), table_name='blogs')
    op.drop_index(op.f('idx_conv_assign_history_conv'), table_name='conversation_assignment_history')
    op.drop_constraint(op.f('conversation_assignment_history_assigned_to_fkey'), 'conversation_assignment_history', type_='foreignkey')
    op.drop_constraint(op.f('conversation_assignment_history_assigned_by_fkey'), 'conversation_assignment_history', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_assignment_history', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conversation_assignment_history', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.alter_column('conversation_notes', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversations', 'reply_mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('conversations', 'rule_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'last_customer_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('conversations', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('unique_customer_per_org'), 'conversations', type_='unique')
    op.drop_constraint(op.f('conversations_campaign_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_index(op.f('uq_customers_org_phone_deleted'), table_name='customers', postgresql_where='(deleted_at IS NULL)')
    op.drop_column('customers', 'instagram_id')
    op.drop_column('customers', 'telegram_chat_id')
    op.drop_index(op.f('idx_kd_content_fts'), table_name='knowledge_documents', postgresql_using='gin')
    op.drop_column('knowledge_documents', 'content')
    op.alter_column('leads', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('leads', 'rule_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_leads_created_at'), table_name='leads')
    op.drop_index(op.f('idx_leads_data'), table_name='leads', postgresql_using='gin')
    op.drop_index(op.f('idx_leads_intent'), table_name='leads')
    op.drop_index(op.f('idx_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('idx_leads_sentiment'), table_name='leads')
    op.drop_index(op.f('idx_leads_status'), table_name='leads')
    op.drop_index(op.f('idx_leads_urgency'), table_name='leads')
    op.drop_constraint(op.f('fk_leads_merged_into'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('leads_assigned_to_fkey'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('fk_leads_campaign'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('leads', 'budget_range')
    op.drop_column('leads', 'merged_into_id')
    op.drop_index(op.f('idx_messages_channel'), table_name='messages')
    op.drop_index(op.f('idx_messages_status'), table_name='messages')
    op.drop_column('messages', 'external_id')
    op.drop_column('messages', 'channel')
    op.alter_column('organization_channels', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('organization_channels', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_org_channels_org'), table_name='organization_channels')
    op.drop_index(op.f('idx_org_channels_type'), table_name='organization_channels')
    op.alter_column('organization_prompts', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_org_prompts_org'), table_name='organization_prompts')
    op.drop_index(op.f('idx_organizations_partner_id'), table_name='organizations')
    op.create_unique_constraint(None, 'organizations', ['whatsapp_phone_number'])
    op.drop_constraint(op.f('organizations_created_by_fkey'), 'organizations', type_='foreignkey')
    op.drop_constraint(op.f('organizations_partner_id_fkey'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'partners', ['partner_id'], ['id'])
    op.drop_column('organizations', 'marketing_message_count')
    op.drop_column('organizations', 'utility_message_count')
    op.drop_column('organizations', 'created_by')
    op.drop_column('organizations', 'last_count_reset')
    op.drop_index(op.f('idx_partners_user_id'), table_name='partners')
    op.create_unique_constraint(None, 'partners', ['user_id'])
    op.alter_column('tags', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tags', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'partners', type_='unique')
    op.create_index(op.f('idx_partners_user_id'), 'partners', ['user_id'], unique=True)
    op.add_column('organizations', sa.Column('last_count_reset', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('utility_message_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('marketing_message_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_partner_id_fkey'), 'organizations', 'partners', ['partner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('organizations_created_by_fkey'), 'organizations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_index(op.f('idx_organizations_partner_id'), 'organizations', ['partner_id'], unique=False)
    op.create_index(op.f('idx_org_prompts_org'), 'organization_prompts', ['organization_id'], unique=False)
    op.alter_column('organization_prompts', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('idx_org_channels_type'), 'organization_channels', ['channel_type'], unique=False)
    op.create_index(op.f('idx_org_channels_org'), 'organization_channels', ['organization_id'], unique=False)
    op.alter_column('organization_channels', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('organization_channels', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('messages', sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('idx_messages_channel'), 'messages', ['channel'], unique=False)
    op.add_column('leads', sa.Column('merged_into_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('budget_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('fk_leads_campaign'), 'leads', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('leads_assigned_to_fkey'), 'leads', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('fk_leads_merged_into'), 'leads', 'leads', ['merged_into_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_leads_urgency'), 'leads', ['urgency'], unique=False)
    op.create_index(op.f('idx_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('idx_leads_sentiment'), 'leads', ['sentiment'], unique=False)
    op.create_index(op.f('idx_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('idx_leads_intent'), 'leads', ['intent'], unique=False)
    op.create_index(op.f('idx_leads_data'), 'leads', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.alter_column('leads', 'rule_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('leads', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('knowledge_documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_kd_content_fts'), 'knowledge_documents', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.add_column('customers', sa.Column('telegram_chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('instagram_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_customers_org_phone_deleted'), 'customers', ['organization_id', 'phone_number'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_foreign_key(op.f('conversations_campaign_id_fkey'), 'conversations', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('unique_customer_per_org'), 'conversations', ['organization_id', 'customer_phone_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('conversations', 'custom_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'last_customer_message_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('conversations', 'rule_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'reply_mode',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('conversation_notes', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'conversation_assignment_history', type_='foreignkey')
    op.drop_constraint(None, 'conversation_assignment_history', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_assignment_history_assigned_by_fkey'), 'conversation_assignment_history', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(op.f('conversation_assignment_history_assigned_to_fkey'), 'conversation_assignment_history', 'users', ['assigned_to'], ['id'])
    op.create_index(op.f('idx_conv_assign_history_conv'), 'conversation_assignment_history', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_blogs_slug'), 'blogs', ['slug'], unique=False)
    op.create_index(op.f('idx_blogs_published'), 'blogs', ['published'], unique=False)
    op.create_unique_constraint(op.f('ai_configurations_organization_id_key'), 'ai_configurations', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.create_table('nano_tasks',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nano_tasks_pkey'))
    )
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meta_template_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_templates_pkey')),
    sa.UniqueConstraint('meta_template_id', name=op.f('whatsapp_templates_meta_template_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_whatsapp_templates_org'), 'whatsapp_templates', ['organization_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('knowledge_chunks_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('knowledge_chunks_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_chunks_pkey'))
    )
    op.create_index(op.f('idx_knowledge_chunks_embedding'), 'knowledge_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.create_table('conversation_custom_field_definitions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('field_label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('field_options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('conversation_custom_field_definitions_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_custom_field_definitions_pkey')),
    sa.UniqueConstraint('organization_id', 'field_name', name=op.f('conversation_custom_field_defini_organization_id_field_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('message_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('message_logs_pkey'))
    )
    op.create_index(op.f('idx_message_logs_org'), 'message_logs', ['organization_id'], unique=False)
    # ### end Alembic commands ###
