"""Add Instagram tables

Revision ID: acd2c8dbf8f6
Revises: a522ec8fa5da
Create Date: 2026-06-17 19:26:40.802341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acd2c8dbf8f6'
down_revision: Union[str, Sequence[str], None] = 'a522ec8fa5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facebook_boosts_org'), table_name='facebook_boosts')
    op.drop_index(op.f('ix_facebook_boosts_post'), table_name='facebook_boosts')
    op.drop_table('facebook_boosts')
    op.drop_index(op.f('idx_knowledge_chunks_embedding'), table_name='knowledge_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_facebook_adsets_organization_id'), table_name='facebook_adsets')
    op.drop_table('facebook_adsets')
    op.drop_index(op.f('ix_facebook_ad_creatives_organization_id'), table_name='facebook_ad_creatives')
    op.drop_table('facebook_ad_creatives')
    op.drop_index(op.f('ix_facebook_posts_org_created'), table_name='facebook_posts')
    op.drop_index(op.f('ix_facebook_posts_org_status'), table_name='facebook_posts')
    op.drop_index(op.f('ix_facebook_posts_organization_id'), table_name='facebook_posts')
    op.drop_index(op.f('ix_facebook_posts_scheduled'), table_name='facebook_posts')
    op.drop_table('facebook_posts')
    op.drop_index(op.f('ix_facebook_pages_org_page'), table_name='facebook_pages')
    op.drop_table('facebook_pages')
    op.drop_index(op.f('ix_ai_recommendations_organization_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('idx_conversation_memory_conv'), table_name='conversation_memory')
    op.drop_index(op.f('idx_conversation_memory_expires'), table_name='conversation_memory')
    op.drop_table('conversation_memory')
    op.drop_index(op.f('idx_whatsapp_templates_org'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    op.drop_table('conversation_custom_field_definitions')
    op.drop_index(op.f('ix_facebook_ads_organization_id'), table_name='facebook_ads')
    op.drop_table('facebook_ads')
    op.drop_index(op.f('ix_facebook_leads_organization_id'), table_name='facebook_leads')
    op.drop_table('facebook_leads')
    op.drop_index(op.f('ix_facebook_campaigns_organization_id'), table_name='facebook_campaigns')
    op.drop_table('facebook_campaigns')
    op.drop_index(op.f('ix_facebook_roi_snapshots_organization_id'), table_name='facebook_roi_snapshots')
    op.drop_table('facebook_roi_snapshots')
    op.drop_index(op.f('idx_message_logs_org'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_index(op.f('ix_facebook_audiences_organization_id'), table_name='facebook_audiences')
    op.drop_table('facebook_audiences')
    op.drop_table('nano_tasks')
    op.drop_constraint(op.f('ai_configurations_organization_id_key'), 'ai_configurations', type_='unique')
    op.drop_index(op.f('idx_blogs_published'), table_name='blogs')
    op.drop_index(op.f('idx_blogs_slug'), table_name='blogs')
    op.alter_column('bookings', 'reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_bookings_lead_id'), table_name='bookings')
    op.alter_column('bot_configs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('bot_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_conv_assign_history_conv'), table_name='conversation_assignment_history')
    op.drop_constraint(op.f('conversation_assignment_history_assigned_by_fkey'), 'conversation_assignment_history', type_='foreignkey')
    op.drop_constraint(op.f('conversation_assignment_history_assigned_to_fkey'), 'conversation_assignment_history', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_assignment_history', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conversation_assignment_history', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.alter_column('conversation_memories', 'facts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('conversation_notes', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversations', 'reply_mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('conversations', 'rule_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'last_customer_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('conversations', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'conversation_stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'greeting'::character varying"))
    op.alter_column('conversations', 'completed_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'recommendation_shown',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_conversations_booking_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_stage'), table_name='conversations')
    op.drop_constraint(op.f('unique_customer_per_org'), 'conversations', type_='unique')
    op.drop_constraint(op.f('conversations_campaign_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_index(op.f('uq_customers_org_phone_deleted'), table_name='customers', postgresql_where='(deleted_at IS NULL)')
    op.drop_column('customers', 'instagram_id')
    op.drop_column('customers', 'telegram_chat_id')
    op.drop_index(op.f('idx_kd_content_fts'), table_name='knowledge_documents', postgresql_using='gin')
    op.drop_column('knowledge_documents', 'content')
    op.alter_column('leads', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('leads', 'rule_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('leads', 'last_scored_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_leads_created_at'), table_name='leads')
    op.drop_index(op.f('idx_leads_data'), table_name='leads', postgresql_using='gin')
    op.drop_index(op.f('idx_leads_intent'), table_name='leads')
    op.drop_index(op.f('idx_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('idx_leads_sentiment'), table_name='leads')
    op.drop_index(op.f('idx_leads_status'), table_name='leads')
    op.drop_index(op.f('idx_leads_urgency'), table_name='leads')
    op.drop_constraint(op.f('leads_assigned_to_fkey'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('fk_leads_campaign'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('fk_leads_merged_into'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('leads', 'budget_range')
    op.drop_column('leads', 'merged_into_id')
    op.alter_column('messages', 'whatsapp_timestamp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_messages_channel'), table_name='messages')
    op.drop_index(op.f('idx_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_mode'), table_name='messages')
    op.drop_column('messages', 'external_id')
    op.drop_column('messages', 'channel')
    op.alter_column('organization_channels', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('organization_channels', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_org_channels_org'), table_name='organization_channels')
    op.drop_index(op.f('idx_org_channels_type'), table_name='organization_channels')
    op.alter_column('organization_prompts', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_org_prompts_org'), table_name='organization_prompts')
    op.drop_index(op.f('idx_organizations_partner_id'), table_name='organizations')
    op.create_unique_constraint(None, 'organizations', ['whatsapp_phone_number'])
    op.drop_constraint(op.f('organizations_partner_id_fkey'), 'organizations', type_='foreignkey')
    op.drop_constraint(op.f('organizations_created_by_fkey'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'partners', ['partner_id'], ['id'])
    op.drop_column('organizations', 'created_by')
    op.drop_column('organizations', 'utility_message_count')
    op.drop_column('organizations', 'marketing_message_count')
    op.drop_column('organizations', 'last_count_reset')
    op.drop_index(op.f('idx_partners_user_id'), table_name='partners')
    op.create_unique_constraint(None, 'partners', ['user_id'])
    op.alter_column('tags', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tags', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'partners', type_='unique')
    op.create_index(op.f('idx_partners_user_id'), 'partners', ['user_id'], unique=True)
    op.add_column('organizations', sa.Column('last_count_reset', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('marketing_message_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('utility_message_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_created_by_fkey'), 'organizations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('organizations_partner_id_fkey'), 'organizations', 'partners', ['partner_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_index(op.f('idx_organizations_partner_id'), 'organizations', ['partner_id'], unique=False)
    op.create_index(op.f('idx_org_prompts_org'), 'organization_prompts', ['organization_id'], unique=False)
    op.alter_column('organization_prompts', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('idx_org_channels_type'), 'organization_channels', ['channel_type'], unique=False)
    op.create_index(op.f('idx_org_channels_org'), 'organization_channels', ['organization_id'], unique=False)
    op.alter_column('organization_channels', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('organization_channels', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('messages', sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_messages_mode'), 'messages', ['mode'], unique=False)
    op.create_index(op.f('idx_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('idx_messages_channel'), 'messages', ['channel'], unique=False)
    op.alter_column('messages', 'whatsapp_timestamp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('leads', sa.Column('merged_into_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('budget_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('fk_leads_merged_into'), 'leads', 'leads', ['merged_into_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_leads_campaign'), 'leads', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('leads_assigned_to_fkey'), 'leads', 'users', ['assigned_to'], ['id'])
    op.create_index(op.f('idx_leads_urgency'), 'leads', ['urgency'], unique=False)
    op.create_index(op.f('idx_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('idx_leads_sentiment'), 'leads', ['sentiment'], unique=False)
    op.create_index(op.f('idx_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('idx_leads_intent'), 'leads', ['intent'], unique=False)
    op.create_index(op.f('idx_leads_data'), 'leads', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.alter_column('leads', 'last_scored_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('leads', 'rule_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('leads', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('knowledge_documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_kd_content_fts'), 'knowledge_documents', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.add_column('customers', sa.Column('telegram_chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('instagram_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_customers_org_phone_deleted'), 'customers', ['organization_id', 'phone_number'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_foreign_key(op.f('conversations_campaign_id_fkey'), 'conversations', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('unique_customer_per_org'), 'conversations', ['organization_id', 'customer_phone_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_conversations_stage'), 'conversations', ['conversation_stage'], unique=False)
    op.create_index(op.f('ix_conversations_booking_status'), 'conversations', ['booking_status'], unique=False)
    op.alter_column('conversations', 'recommendation_shown',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'completed_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'conversation_stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'greeting'::character varying"))
    op.alter_column('conversations', 'custom_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'last_customer_message_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('conversations', 'rule_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'reply_mode',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('conversation_notes', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversation_memories', 'facts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'conversation_assignment_history', type_='foreignkey')
    op.drop_constraint(None, 'conversation_assignment_history', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_assignment_history_assigned_to_fkey'), 'conversation_assignment_history', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('conversation_assignment_history_assigned_by_fkey'), 'conversation_assignment_history', 'users', ['assigned_by'], ['id'])
    op.create_index(op.f('idx_conv_assign_history_conv'), 'conversation_assignment_history', ['conversation_id'], unique=False)
    op.alter_column('bot_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('bot_configs', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('ix_bookings_lead_id'), 'bookings', ['lead_id'], unique=False)
    op.alter_column('bookings', 'reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_blogs_slug'), 'blogs', ['slug'], unique=False)
    op.create_index(op.f('idx_blogs_published'), 'blogs', ['published'], unique=False)
    op.create_unique_constraint(op.f('ai_configurations_organization_id_key'), 'ai_configurations', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.create_table('nano_tasks',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nano_tasks_pkey'))
    )
    op.create_table('facebook_audiences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meta_audience_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('audience_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('targeting_spec', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_audiences_pkey')),
    sa.UniqueConstraint('meta_audience_id', name=op.f('facebook_audiences_meta_audience_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_facebook_audiences_organization_id'), 'facebook_audiences', ['organization_id'], unique=False)
    op.create_table('message_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('message_logs_pkey'))
    )
    op.create_index(op.f('idx_message_logs_org'), 'message_logs', ['organization_id'], unique=False)
    op.create_table('facebook_roi_snapshots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('spend_cents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revenue_cents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('leads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_roi_snapshots_pkey'))
    )
    op.create_index(op.f('ix_facebook_roi_snapshots_organization_id'), 'facebook_roi_snapshots', ['organization_id'], unique=False)
    op.create_table('facebook_campaigns',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meta_campaign_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('objective', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('daily_budget_cents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lifetime_budget_cents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('special_ad_categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_campaigns_pkey')),
    sa.UniqueConstraint('meta_campaign_id', name=op.f('facebook_campaigns_meta_campaign_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_facebook_campaigns_organization_id'), 'facebook_campaigns', ['organization_id'], unique=False)
    op.create_table('facebook_leads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('leadgen_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ad_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('form_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('matched_crm_lead_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('attributed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_leads_pkey')),
    sa.UniqueConstraint('leadgen_id', name=op.f('facebook_leads_leadgen_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_facebook_leads_organization_id'), 'facebook_leads', ['organization_id'], unique=False)
    op.create_table('facebook_ads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('adset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('creative_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('meta_ad_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['adset_id'], ['facebook_adsets.id'], name=op.f('facebook_ads_adset_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['facebook_campaigns.id'], name=op.f('facebook_ads_campaign_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_id'], ['facebook_ad_creatives.id'], name=op.f('facebook_ads_creative_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_ads_pkey')),
    sa.UniqueConstraint('meta_ad_id', name=op.f('facebook_ads_meta_ad_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_facebook_ads_organization_id'), 'facebook_ads', ['organization_id'], unique=False)
    op.create_table('conversation_custom_field_definitions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('field_label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('field_options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('conversation_custom_field_definitions_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_custom_field_definitions_pkey')),
    sa.UniqueConstraint('organization_id', 'field_name', name=op.f('conversation_custom_field_defini_organization_id_field_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meta_template_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_templates_pkey')),
    sa.UniqueConstraint('meta_template_id', name=op.f('whatsapp_templates_meta_template_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_whatsapp_templates_org'), 'whatsapp_templates', ['organization_id'], unique=False)
    op.create_table('conversation_memory',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_memory_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_memory_pkey'))
    )
    op.create_index(op.f('idx_conversation_memory_expires'), 'conversation_memory', ['expires_at'], unique=False)
    op.create_index(op.f('idx_conversation_memory_conv'), 'conversation_memory', ['conversation_id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_applied', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_recommendations_pkey'))
    )
    op.create_index(op.f('ix_ai_recommendations_organization_id'), 'ai_recommendations', ['organization_id'], unique=False)
    op.create_table('facebook_pages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('page_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('follower_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_pages_pkey'))
    )
    op.create_index(op.f('ix_facebook_pages_org_page'), 'facebook_pages', ['organization_id', 'page_id'], unique=True)
    op.create_table('facebook_posts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('meta_post_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boost_campaign_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_scheduled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_posts_pkey'))
    )
    op.create_index(op.f('ix_facebook_posts_scheduled'), 'facebook_posts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_facebook_posts_organization_id'), 'facebook_posts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_facebook_posts_org_status'), 'facebook_posts', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_facebook_posts_org_created'), 'facebook_posts', ['organization_id', 'created_at'], unique=False)
    op.create_table('facebook_ad_creatives',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meta_creative_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('headline', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cta_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cta_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_ad_creatives_pkey')),
    sa.UniqueConstraint('meta_creative_id', name=op.f('facebook_ad_creatives_meta_creative_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_facebook_ad_creatives_organization_id'), 'facebook_ad_creatives', ['organization_id'], unique=False)
    op.create_table('facebook_adsets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('meta_adset_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('daily_budget_cents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lifetime_budget_cents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('targeting', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['facebook_campaigns.id'], name=op.f('facebook_adsets_campaign_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_adsets_pkey')),
    sa.UniqueConstraint('meta_adset_id', name=op.f('facebook_adsets_meta_adset_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_facebook_adsets_organization_id'), 'facebook_adsets', ['organization_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('knowledge_chunks_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('knowledge_chunks_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_chunks_pkey'))
    )
    op.create_index(op.f('idx_knowledge_chunks_embedding'), 'knowledge_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.create_table('facebook_boosts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meta_campaign_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta_adset_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta_ad_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_budget_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('targeting', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('goal', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cta_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('advantage_audience', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('advantage_creative', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('special_ad_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('estimated_reach', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spent_so_far', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('facebook_boosts_pkey'))
    )
    op.create_index(op.f('ix_facebook_boosts_post'), 'facebook_boosts', ['post_id'], unique=False)
    op.create_index(op.f('ix_facebook_boosts_org'), 'facebook_boosts', ['organization_id'], unique=False)
    # ### end Alembic commands ###
